spring:
  application:
    name: spring-jpa1

  datasource:
    url: jdbc:h2:tcp://localhost/~/spring-jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: debug